pageInfo:
  title: "Home Dashboard"
  description: "Übersicht über meine lokalen Services"

appConfig:
  theme: colorful

sections:
  - name: "Services"
    icon: "fas fa-th"
    items:
      - title: "Bichon"
        description: "Local Service"
        icon: "fas fa-dog"
        url: "http://192.168.178.80:15630"

      - title: "Filebrowser"
        description: "Browse SSD & Backups"
        icon: "fas fa-folder-open"
        url: "http://192.168.178.80:8082"

      - title: "Paperless"
        description: "Dokumentenverwaltung"
        icon: "fas fa-file-alt"
        url: "http://192.168.178.80:8000"

      - title: "Portainer"
        description: "Docker Management"
        icon: "fab fa-docker"
        url: "http://192.168.178.80:9000"
