version: "3.8"

services:
  dashy:
    image: lissy93/dashy:arm64v8
    container_name: dashy
    volumes:
      - ./config:/app/user-data
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "/app/services/healthcheck"]
      interval: 90s
      timeout: 10s
      retries: 3
      start_period: 40s
