services:
  dashy:
    image: lissy93/dashy:3.0.1
    container_name: dashy
    volumes:
      - ./config:/app/user-data
    ports:
      - "0.0.0.0:8090:80"
    environment:
      - NODE_ENV=production
      - DASHY_CONF_FILE=/app/user-data/conf.yml
    command: ["node", "server"]
    restart: unless-stopped
